import { useState } from 'react';
import * as Icons from 'lucide-react';
import { evidence, sourceEvents } from '../data/mockData';
import { MediaArtwork, Waveform } from './Visuals';
const tabs = ['Overview','Visual Forensics','Metadata','AI Signals','Source Trace'];
const rows = [['AI Detection','Synthetic characteristics','91%','Warning'],['Metadata','EXIF missing','84%','Warning'],['Image Forensics','Artifacts detected','88%','Warning'],['Source Trace','Earlier version found','76%','Review'],['Context','Claim differs from source','82%','Warning']];
export default function ResultsView({ media={name:'portrait_01.jpg', type:'image/jpeg'} }) { const [tab,setTab]=useState('Overview'); const video=media.type?.startsWith('video'), audio=media.type?.startsWith('audio'); const report=media.report; const metrics=report?.metrics || {ai_generated:87,manipulated:52,authentic:14}; const confidence=report?.confidence || 87; return <main className="results-page container"><div className="result-title"><div><span className="eyebrow">ANALYSIS REPORT</span><h1>Analysis result</h1><p>{media.name} · Completed just now</p></div><button className="btn btn-outline"><Icons.Download size={17}/> Export report</button></div><section className="verdict-overview"><div className="result-media"><MediaArtwork/>{audio&&<Waveform/>}</div><div className="verdict-content"><span className="status-label warning"><Icons.TriangleAlert size={15}/> {report?.verdict || 'Likely AI-Generated'}</span><h2>Multiple signals deserve a closer look.</h2><p>{report?.disclaimer || 'Our models found synthetic-generation characteristics. Treat this as a directional assessment and corroborate it with independent evidence.'}</p><div className="confidence-list">{[['AI Generated',metrics.ai_generated,'cyan'],['Manipulated',metrics.manipulated,'purple'],['Authentic',metrics.authentic,'muted']].map(([label,value,tone])=><div key={label}><span>{label}<b>{value}%</b></span><i className={tone}><em style={{width:`${value}%`}}/></i></div>)}</div></div><div className="confidence-ring"><svg viewBox="0 0 120 120"><circle cx="60" cy="60" r="50"/><circle className="ring-value" cx="60" cy="60" r="50" pathLength="100" style={{strokeDasharray:`${confidence} 100`}}/></svg><div><b>{confidence}%</b><small>confidence</small></div></div></section><div className="tabs" role="tablist">{tabs.map(t=><button className={tab===t?'active':''} key={t} onClick={()=>setTab(t)} role="tab">{t}</button>)}</div>{tab==='Overview' && <Overview evidenceItems={report?.evidence}/>} {tab==='Visual Forensics' && <Forensics video={video}/>} {tab==='Metadata' && <Metadata/>} {tab==='AI Signals' && <Signals/>} {tab==='Source Trace' && <SourceTrace events={report?.source_events}/>}</main> }
function Overview({evidenceItems}){const items=(evidenceItems || evidence).map(item=>({...item,text:item.text || item.description}));return <><section className="section-heading left"><span className="eyebrow">EXPLAINABLE AI</span><h2>Why we think this</h2><p>Independent signals make the assessment transparent and reviewable.</p></section><div className="evidence-grid">{items.map(item=>{const I=Icons[item.icon]||Icons.Search;return <article className="evidence-card" key={item.title}><span className="evidence-icon"><I size={20}/></span><div className="evidence-head"><h3>{item.title}</h3><span className={`severity ${item.severity.toLowerCase()}`}>{item.severity}</span></div><p>{item.text}</p><div className="evidence-confidence"><span>Signal confidence</span><b>{item.confidence}%</b><i><em style={{width:`${item.confidence}%`}}/></i></div></article>})}</div><EvidenceTable/><FinalVerdict/></>}
function Forensics({video}){return <section className="forensic-panel"><div className="forensic-preview"><MediaArtwork/><span className="face-box one">Face: 94%</span><span className="face-box two">Artifact region</span></div><div><span className="eyebrow">VISUAL FORENSICS</span><h2>Artifact map</h2><p>Highlighted zones mark regions with irregular texture and blending patterns.</p><ul className="forensic-list"><li><b>01</b> Facial boundary inconsistency</li><li><b>02</b> Background depth irregularity</li><li><b>03</b> Compression pattern shift</li></ul></div>{video&&<div className="video-timeline"><h3>Frame analysis</h3><div className="timeline-line">{['00:04','00:08','00:12','00:16','00:20'].map((time,i)=><button key={time} className={i===2||i===4?'clean':'flagged'}>{time}<span>{i===2||i===4?'✓':'⚠'}</span></button>)}</div></div>}</section>}
function Metadata(){return <section className="metadata-card"><Icons.FileSearch/><div><span className="eyebrow">METADATA INSPECTION</span><h2>Limited provenance data available</h2><p>No original EXIF camera fields were present. This can happen during normal sharing, but removes a useful source-verification signal.</p></div><dl><div><dt>Capture device</dt><dd>Not available</dd></div><div><dt>Creation date</dt><dd>Not available</dd></div><div><dt>Editing software</dt><dd>Not available</dd></div></dl></section>}
function Signals(){return <section className="signal-grid"><div><Icons.BrainCircuit/><h2>Model consensus</h2><p>4 of 5 independent detectors found synthetic-media characteristics.</p></div><div className="signal-bars">{['Texture consistency','Reflectance cues','Noise distribution','Semantic coherence'].map((x,i)=><span key={x}>{x}<i><em style={{width:`${92-i*11}%`}}/></i></span>)}</div></section>}
export function SourceTrace({events=sourceEvents}){return <section className="source-section"><div className="section-heading left"><span className="eyebrow">SOURCETRACE</span><h2>Where did this content come from?</h2><p>Track how this media moved and changed across the web.</p></div><div className="trace-layout"><div className="source-timeline">{events.map((e,i)=><article key={e.source}><span className={`timeline-dot ${e.status.toLowerCase()}`}>{i+1}</span><time>{e.date}</time><h3>{e.source} <small>{e.platform}</small></h3><p>{e.caption}</p><a href="#trace">View archived URL ↗</a></article>)}</div><aside className="source-summary"><div><small>Earliest Known Source</small><b>Unknown / Unverified</b></div><div><small>Source Credibility</small><b className="medium">Medium</b></div><div><small>Context Changes</small><b className="warning-text">Potentially misleading</b></div></aside></div></section>}
function EvidenceTable(){return <section className="table-section"><div className="section-heading left"><span className="eyebrow">EVIDENCE SUMMARY</span><h2>Signals at a glance</h2></div><div className="table-wrap"><table><thead><tr><th>Signal</th><th>Result</th><th>Confidence</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r[0]}>{r.map((c,i)=><td key={c}>{i===3?<span className="status-label warning">{c}</span>:c}</td>)}</tr>)}</tbody></table></div></section>}
function FinalVerdict(){return <section className="final-verdict"><span className="status-label warning"><Icons.TriangleAlert size={15}/> POTENTIALLY MANIPULATED</span><h2>Overall confidence: <strong>91%</strong></h2><p>This assessment is based on multiple independent signals. These signals increase the likelihood of manipulation, but they do not by themselves prove that the content is falsified.</p></section>}
