import { Link } from 'react-router-dom';
import { ArrowRight, AudioLines, BrainCircuit, CheckCircle2, Eye, FileSearch, Fingerprint, Image, LocateFixed, ShieldCheck, Sparkles, Video } from 'lucide-react';
import AnalysisWorkspace from '../components/AnalysisWorkspace';
import { MediaArtwork, Waveform } from '../components/Visuals';
import { recentAnalyses } from '../data/mockData';
const features=[['BrainCircuit','AI Detection','Advanced models detect AI-generated or manipulated content.'],['Eye','Explainable Results','Understand exactly why the system reached its assessment.'],['LocateFixed','Source Tracing','Find original sources and understand how content spread.'],['AudioLines','Multi-Format Support','Analyze images, videos, audio, and more.'],['Fingerprint','Evidence-Based Analysis','Combine multiple signals instead of a single prediction.'],['ShieldCheck','Built for Impact','Designed for journalists, researchers, and everyday citizens.']];
export default function Home({onAnalyze}){return <><main><section className="hero container"><div className="hero-copy"><span className="eyebrow">TRUTH IN A SYNTHETIC WORLD</span><h1>Detect.<br/>Explain.<br/><span>Verify.</span></h1><p className="hero-lead">AI-powered media verification for a more trustworthy internet.</p><p className="hero-description">Analyze images, audio, and video to detect potential AI generation or manipulation, understand the reasoning, and trace the original source — before you trust or share.</p><div className="hero-buttons"><Link className="btn" to="/analyze">Start Verifying <ArrowRight size={17}/></Link><a className="btn btn-outline" href="#how">Learn More</a></div></div><HeroVisual/></section><section className="container hero-stats">{[['3+','Media Types','Image, Video, Audio'],['AI','Powered Analysis','Advanced media intelligence'],['Trusted','For Journalists & Researchers','and everyday users']].map(s=><div key={s[0]}><b>{s[0]}</b><span>{s[1]}</span><small>{s[2]}</small></div>)}</section><section className="container" id="analyze"><AnalysisWorkspace onAnalyze={onAnalyze}/></section><section className="container features" id="how"><div className="section-heading"><span className="eyebrow">BUILT FOR CLARITY</span><h2>Evidence, not empty verdicts.</h2><p>Every assessment is designed to help you make a more informed next decision.</p></div><div className="feature-grid">{features.map(([icon,title,text])=>{const I={BrainCircuit,Eye,LocateFixed,AudioLines,Fingerprint,ShieldCheck}[icon];return <article className="feature-card" key={title}><span><I size={21}/></span><h3>{title}</h3><p>{text}</p><ArrowRight size={17}/></article>})}</div></section><Recent/><Extension/></main></>}
function HeroVisual(){return <div className="hero-visual"><div className="orb orb-one"/><div className="orb orb-two"/><div className="hero-main-card"><div className="card-top"><span><Sparkles size={14}/> Live signal scan</span><i/></div><MediaArtwork/><div className="card-caption"><span><Image size={15}/> image_01.jpg</span><b>87% synthetic likelihood</b></div></div><div className="floating-card video-card"><span className="mini-icon"><Video size={16}/></span><div><b>Video frames</b><small>12 signals analyzed</small></div><CheckCircle2 size={18}/></div><div className="floating-card audio-card"><span className="mini-icon purple"><AudioLines size={16}/></span><div><b>Voice analysis</b><Waveform/></div></div><span className="signal-badge ai">✦ AI Generated?</span><span className="signal-badge deepfake">◉ Deepfake?</span><span className="signal-badge authentic">✓ Authentic?</span></div>}
function Recent(){return <section className="container recent"><div className="section-heading left"><span className="eyebrow">YOUR WORKSPACE</span><h2>Recent analyses</h2><p>Mock records demonstrate how your analysis history will appear.</p></div><div className="recent-grid">{recentAnalyses.map((x,i)=><article key={x.name}><div className={`recent-thumb t${i}`}><FileSearch size={22}/></div><div><h3>{x.name}</h3><p>{x.time}</p></div><span className={`status-label ${x.tone}`}>{x.result}</span><b>{x.confidence}%</b></article>)}</div></section>}
function Extension(){return <section className="container extension"><div><span className="eyebrow">TRUTHLENS EXTENSION</span><h2>Verify what you see, anywhere.</h2><p>See suspicious media while browsing? Verify it instantly with the TruthLens browser extension.</p><button className="btn">Add to Browser <ArrowRight size={17}/></button></div><div className="extension-popup"><header><ShieldCheck size={18}/> <b>TruthLens</b><span>•••</span></header><div className="popup-warning">⚠ <b>Potentially<br/>Manipulated</b></div><p>Confidence: <strong>86%</strong></p><hr/><small>Why?</small><ul><li>Synthetic artifacts</li><li>Missing metadata</li><li>Source uncertain</li></ul><button>View Full Analysis <ArrowRight size={15}/></button></div></section>}
